# Generated by Django 5.2.3 on 2025-07-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0002_remove_video_video_url_video_video_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together={('user', 'video')},
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='progress_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='watchhistory',
            name='progress',
        ),
    ]
