# Generated by Django 5.2.3 on 2025-07-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0003_alter_watchhistory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
