# Generated by Django 5.2.3 on 2025-07-16 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0004_video_is_featured_video_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_new',
        ),
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 16, 9, 52, 47, 779887, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
